### ISSUE TITLE
Set up fonts

### ISSUE THREAD

**Issue by MariaGarciaCS** [ITMD362-Team-Shaky-Techy/Project-2#4]
- [x] Select font sizes for common elements (h1, h2, h3, p...etc.) according to modular scale
- [x] Import and apply fonts from google fonts
- [x] Make sure fonts have a web-safe backup

**Comment by NgoQuocBao1010** [comment]
Hi, can I help with this issue please?

**Comment by MariaGarciaCS** [comment]
No, sorry this is a private project for a class

**Comment by MariaGarciaCS** [comment]
Google Fonts Considered


- Crimson Text
- Merriweather
- Playfair Display 
- PT Serif
- Lora 
- Lato 
- Libre Baskerville
- Shrikhand
- Chivo
